"use client";

import { useEffect } from 'react';
import mermaid from 'mermaid';

// Configure Mermaid settings for our dark theme
mermaid.initialize({
  startOnLoad: false,
  theme: 'dark',
  securityLevel: 'loose',
  themeVariables: {
    background: '#0c0c0e',
    primaryColor: '#6366f1',
    primaryTextColor: '#f3f4f6',
    lineColor: '#3a3a46',
  }
});

export function MermaidRenderer() {
  useEffect(() => {
    const renderDiagrams = async () => {
      // Find all code blocks generated by the markdown parser with language-mermaid
      const elements = document.querySelectorAll('code.language-mermaid');
      
      for (let i = 0; i < elements.length; i++) {
        const element = elements[i] as HTMLElement;
        const parent = element.parentElement; // This is the <pre> block
        if (!parent) continue;

        const code = element.textContent || '';
        const id = `mermaid-diagram-${i}`;

        try {
          // Compile graph to SVG
          const { svg } = await mermaid.render(id, code);
          
          // Create wrapper container
          const wrapper = document.createElement('div');
          wrapper.className = "mermaid-chart-wrapper my-8 p-6 bg-neutral-950/40 border border-neutral-800/80 rounded-2xl overflow-x-auto flex justify-center";
          wrapper.innerHTML = svg;

          // Swap out the <pre> tag with our rendered SVG block
          parent.parentNode?.replaceChild(wrapper, parent);
        } catch (error) {
          console.error("Error compiling mermaid graph:", error);
          // If compilation fails (e.g. syntax error), keep the raw code visible
        }
      }
    };

    renderDiagrams();
  }, []);

  return null;
}
